repos:
  - repo: github.com/pre-commit-hook.git
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: double-quote-string-fixer
    -   id: name-tests-test
        args: ['--pytest-test-first']
        exclude: ^tests/conftest\.py$|^tests/.*fixtures\.py$
    -   id: requirements-txt-fixer
  - repo: github.com/pycqa_isort.git
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/hhatto/autopep8
    rev: v2.3.1
    hooks:
      - id: autopep8
#  - repo: https://github.com/psf/black
#    rev: 24.8.0
#    hooks:
#    -   id: black
#  - repo: https://github.com/PyCQA/flake8
#    rev: 7.1.1
#    hooks:
#      - id: flake8
#        name: flake8 (py312)
#        language_version`: python3.12

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.8.12
    hooks:
      - id: uv-lock